import { execFileSync } from "node:child_process";
import { mkdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { CATALOGUE_PATH, ICON_LIST_PATH, scanUsedIcons } from "./icon-scan";

// `npm run gen:icons`: refresh the font's ligature catalogue, rescan src for
// icon names, rewrite the committed list, and rebuild the subset font served
// from /fonts. Needs Python fontTools + brotli (`python -m pip install
// fonttools brotli`). Run after adding an icon; scripts/icon-scan.test.ts
// fails until you do.
const root = process.cwd();
const input = join(root, "node_modules/material-symbols/material-symbols-rounded.woff2");
const python = process.env.PYTHON ?? "python";

// Catalogue first: the scan only keeps names the font can actually draw.
execFileSync(python, [join(root, "scripts/subset-icons.py"), "--catalogue", input, join(root, CATALOGUE_PATH)], {
  stdio: "inherit",
});

const names = scanUsedIcons(root);
writeFileSync(
  join(root, ICON_LIST_PATH),
  `# Material Symbols Rounded ligatures used in src. Generated by \`npm run gen:icons\`.\n${names.join("\n")}\n`,
);

const out = join(root, "public/fonts/material-symbols-rounded-subset.woff2");
mkdirSync(join(root, "public/fonts"), { recursive: true });
execFileSync(python, [join(root, "scripts/subset-icons.py"), input, join(root, ICON_LIST_PATH), out], {
  stdio: "inherit",
});
console.log(`${names.length} icons, ${statSync(out).size} bytes (full font: ${statSync(input).size})`);
