-- ============================================================================
-- 0075_clear_business_data.sql - NEUTRALISED 2026-10-03 (full audit)
--
-- This file used to be a one-off DATA RESET: it disabled the ledger, receipt,
-- fraud, notification and audit immutability triggers and ran
-- `truncate table public.businesses cascade`, wiping every tenant, the points
-- ledger and the audit trail. A data reset is an operator action, not schema
-- history - and because migrations replay on every new environment, branch DB
-- or `supabase db push`, leaving it here meant any replay would wipe that
-- environment again.
--
-- It already ran on production (zlfxfzlnklqhajacngxf) before this change.
-- The body is removed and the file kept as a no-op so the numbered sequence
-- stays intact. NEVER restore the old body and NEVER paste it into the SQL
-- Editor: the original text is in git history (before commit "chore(db):
-- neutralise the 0075 and 0077 data-wipe migrations") for reference only.
-- ============================================================================
