-- ============================================================================
-- 0077_force_delete_business.sql - NEUTRALISED 2026-10-03 (full audit)
--
-- This file used to do two dangerous things:
--   1. create public.force_delete_business(uuid): SECURITY DEFINER, no caller
--      check, disabled the append-only triggers and deleted a tenant INCLUDING
--      its audit_logs, writing no audit row. Its grants never revoked
--      Supabase's default PUBLIC execute, so anyone with the anon key could
--      call it. 0080 revoked it, 0081 dropped it, and after a later re-run of
--      this file re-created it, it was dropped again by hand.
--   2. a standalone block that deleted EVERY business, the whole points ledger
--      and all audit_logs as plain top-level statements.
--
-- Both ran on production (zlfxfzlnklqhajacngxf) before this change. A replay
-- (new environment, branch DB, `supabase db push`) would have re-created the
-- public delete function and wiped that environment, so the body is removed
-- and the file kept as a no-op to preserve the numbered sequence. The audited,
-- super_admin-only purge lives in purge_business / purge_all_businesses (0081).
--
-- NEVER restore the old body and NEVER paste it into the SQL Editor. The
-- original text is in git history for reference only.
-- ============================================================================
